### ISSUE TITLE
nested classes ignored

### ISSUE THREAD

**Issue by dwatkinsweb** [xhtml2pdf/xhtml2pdf#224]
Nested classes don't appear to be read or implemented properly.

I use the following for tables #details is a table or a div surrounding a table (tried both ways), the first class (names, networks, body) is the tr, and the second class (current, alternate_0) is the td. The third style is set for everything so all cells have #eeeeee instead of each row being a different color. I have to do .current_name, .current_network, .current_body which I don't really care for in order to get the correct effect.

This doesn't work
```css
#details .names .current,
#details .names .alternate_0 {
    background-color: #aaaaaa;
}
#details .networks .current,
#details .networks .alternate_0 {
    background-color: #cccccc;
}
#details .body .current,
#details .body .alternate_0 {
    background-color: #eeeeee;
}
````

This does work
```css
#details .current_name,
#details .alternate_0_name {
    background-color: #aaaaaa;
}
#details .current_network,
#details .alternate_0_network {
    background-color: #cccccc;
}
#details .current_body,
#details .alternate_0_body {
    background-color: #eeeeee;
}
```
