### ISSUE TITLE
Issue with different font types and same name

### ISSUE THREAD

**Issue by kostyachum** [xhtml2pdf/xhtml2pdf#381]
Hi,
I've spent some time to solve this issue, so I guess it could be helpful for somebody.

When having two font faces for `regular` and `bold` like this:

```css
@font-face {
    font-family: CVFont;
    src: url("fonts/Microsoft YaHei.ttf");
}

@font-face {
    font-family: CVFont;
    src: url("Microsoft YaHei Bold.ttf");
    font-weight: bold;
}
```
In case if fonts have the same name in the meta the behavior is bit unexpected - the seconds font-face will be the same as first one.
The key is in the info:
![screenshot from 2018-01-03 16-29-30](https://user-images.githubusercontent.com/5758428/34524303-bfa52e1c-f0a3-11e7-8380-9cd97f3c23f6.png)
![screenshot from 2018-01-03 16-33-12](https://user-images.githubusercontent.com/5758428/34524316-cf06b150-f0a3-11e7-85b1-ecd87ed68a2b.png)

I've had to change the name in the font's meta manually to resolve this issue, but I think the fix should be pretty straightforward.
